DROP TABLE IF EXISTS invoice_line CASCADE;
DROP TABLE IF EXISTS invoice CASCADE;
DROP TABLE IF EXISTS invoice_status CASCADE;
DROP TABLE IF EXISTS exchange_rate CASCADE;
DROP TABLE IF EXISTS tax CASCADE;

DROP TABLE IF EXISTS refund CASCADE;
DROP TABLE IF EXISTS payment_transaction CASCADE;
DROP TABLE IF EXISTS payment CASCADE;
DROP TABLE IF EXISTS payment_method CASCADE;
DROP TABLE IF EXISTS payment_status CASCADE;

DROP TABLE IF EXISTS boarding_validation CASCADE;
DROP TABLE IF EXISTS boarding_pass CASCADE;
DROP TABLE IF EXISTS check_in CASCADE;
DROP TABLE IF EXISTS check_in_status CASCADE;
DROP TABLE IF EXISTS boarding_group CASCADE;

DROP TABLE IF EXISTS baggage CASCADE;
DROP TABLE IF EXISTS seat_assignment CASCADE;
DROP TABLE IF EXISTS ticket_segment CASCADE;
DROP TABLE IF EXISTS ticket CASCADE;
DROP TABLE IF EXISTS sale CASCADE;
DROP TABLE IF EXISTS reservation_passenger CASCADE;
DROP TABLE IF EXISTS reservation CASCADE;
DROP TABLE IF EXISTS ticket_status CASCADE;
DROP TABLE IF EXISTS fare CASCADE;
DROP TABLE IF EXISTS fare_class CASCADE;
DROP TABLE IF EXISTS sale_channel CASCADE;
DROP TABLE IF EXISTS reservation_status CASCADE;

DROP TABLE IF EXISTS flight_delay CASCADE;
DROP TABLE IF EXISTS flight_segment CASCADE;
DROP TABLE IF EXISTS flight CASCADE;
DROP TABLE IF EXISTS delay_reason_type CASCADE;
DROP TABLE IF EXISTS flight_status CASCADE;

DROP TABLE IF EXISTS maintenance_event CASCADE;
DROP TABLE IF EXISTS maintenance_type CASCADE;
DROP TABLE IF EXISTS maintenance_provider CASCADE;
DROP TABLE IF EXISTS aircraft_seat CASCADE;
DROP TABLE IF EXISTS aircraft_cabin CASCADE;
DROP TABLE IF EXISTS aircraft CASCADE;
DROP TABLE IF EXISTS cabin_class CASCADE;
DROP TABLE IF EXISTS aircraft_model CASCADE;
DROP TABLE IF EXISTS aircraft_manufacturer CASCADE;

DROP TABLE IF EXISTS airport_regulation CASCADE;
DROP TABLE IF EXISTS runway CASCADE;
DROP TABLE IF EXISTS boarding_gate CASCADE;
DROP TABLE IF EXISTS terminal CASCADE;
DROP TABLE IF EXISTS airport CASCADE;

DROP TABLE IF EXISTS customer_benefit CASCADE;
DROP TABLE IF EXISTS miles_transaction CASCADE;
DROP TABLE IF EXISTS loyalty_account_tier CASCADE;
DROP TABLE IF EXISTS loyalty_account CASCADE;
DROP TABLE IF EXISTS customer CASCADE;
DROP TABLE IF EXISTS loyalty_tier CASCADE;
DROP TABLE IF EXISTS loyalty_program CASCADE;
DROP TABLE IF EXISTS benefit_type CASCADE;
DROP TABLE IF EXISTS customer_category CASCADE;

DROP TABLE IF EXISTS audit_session_event CASCADE;
DROP TABLE IF EXISTS audit_event_field_change CASCADE;
DROP TABLE IF EXISTS audit_event CASCADE;
DROP TABLE IF EXISTS audit_resource_type CASCADE;
DROP TABLE IF EXISTS audit_action_type CASCADE;

DROP TABLE IF EXISTS role_permission CASCADE;
DROP TABLE IF EXISTS user_role CASCADE;
DROP TABLE IF EXISTS user_account CASCADE;
DROP TABLE IF EXISTS security_permission CASCADE;
DROP TABLE IF EXISTS security_role CASCADE;
DROP TABLE IF EXISTS user_status CASCADE;

DROP TABLE IF EXISTS person_contact CASCADE;
DROP TABLE IF EXISTS person_document CASCADE;
DROP TABLE IF EXISTS person CASCADE;
DROP TABLE IF EXISTS contact_type CASCADE;
DROP TABLE IF EXISTS document_type CASCADE;
DROP TABLE IF EXISTS person_type CASCADE;

DROP TABLE IF EXISTS airline CASCADE;

DROP TABLE IF EXISTS currency CASCADE;
DROP TABLE IF EXISTS address CASCADE;
DROP TABLE IF EXISTS district CASCADE;
DROP TABLE IF EXISTS city CASCADE;
DROP TABLE IF EXISTS state_province CASCADE;
DROP TABLE IF EXISTS country CASCADE;
DROP TABLE IF EXISTS continent CASCADE;
DROP TABLE IF EXISTS time_zone CASCADE;
