INSERT INTO security_permission (permission_code, permission_name, permission_description)
VALUES
    ('SECURITY.USERS_MANAGE', 'Manage Users', 'Create and update user accounts and statuses.'),
    ('SECURITY.ROLES_MANAGE', 'Manage Roles', 'Create and update security roles.'),
    ('SECURITY.PERMISSIONS_MANAGE', 'Manage Permissions', 'Create and update security permissions.'),
    ('SECURITY.ROLE_ASSIGN', 'Assign Roles', 'Assign roles to user accounts.'),
    ('IDENTITY.READ', 'Read Identity', 'Read identity data.'),
    ('IDENTITY.WRITE', 'Write Identity', 'Create and update identity data.'),
    ('GEOGRAPHY.READ', 'Read Geography', 'Read geography and reference data.'),
    ('GEOGRAPHY.WRITE', 'Write Geography', 'Create and update geography and reference data.'),
    ('AIRLINE.READ', 'Read Airline', 'Read airline data.'),
    ('AIRLINE.WRITE', 'Write Airline', 'Create and update airline data.'),
    ('AIRPORT.READ', 'Read Airport', 'Read airport data.'),
    ('AIRPORT.WRITE', 'Write Airport', 'Create and update airport data.'),
    ('AIRCRAFT.READ', 'Read Aircraft', 'Read aircraft data.'),
    ('AIRCRAFT.WRITE', 'Write Aircraft', 'Create and update aircraft data.'),
    ('FLIGHT_OPS.READ', 'Read Flight Operations', 'Read flight operations data.'),
    ('FLIGHT_OPS.WRITE', 'Write Flight Operations', 'Create and update flight operations data.'),
    ('SALES.READ', 'Read Sales', 'Read reservation and ticketing data.'),
    ('SALES.WRITE', 'Write Sales', 'Create and update reservation and ticketing data.'),
    ('BOARDING.READ', 'Read Boarding', 'Read check-in and boarding data.'),
    ('BOARDING.WRITE', 'Write Boarding', 'Create and update check-in and boarding data.'),
    ('PAYMENT.READ', 'Read Payment', 'Read payment data.'),
    ('PAYMENT.WRITE', 'Write Payment', 'Create and update payment and refund data.'),
    ('BILLING.READ', 'Read Billing', 'Read billing data.'),
    ('BILLING.WRITE', 'Write Billing', 'Create and update invoices, taxes and exchange rates.'),
    ('LOYALTY.READ', 'Read Loyalty', 'Read customer loyalty data.'),
    ('LOYALTY.WRITE', 'Write Loyalty', 'Create and update customer loyalty data.'),
    ('AUDIT.READ', 'Read Audit', 'Read audit events and change logs.'),
    ('AUDIT.WRITE', 'Write Audit', 'Create and update audit controls and metadata.'),
    ('SYSTEM.CONFIGURE', 'Configure System', 'Execute system-level configuration operations.')
ON CONFLICT (permission_code) DO UPDATE
SET
    permission_name = EXCLUDED.permission_name,
    permission_description = EXCLUDED.permission_description,
    updated_at = now();

WITH role_perm(role_code, permission_code) AS (
    VALUES
        ('PLATFORM_ADMIN', 'SECURITY.USERS_MANAGE'),
        ('PLATFORM_ADMIN', 'SECURITY.ROLES_MANAGE'),
        ('PLATFORM_ADMIN', 'SECURITY.PERMISSIONS_MANAGE'),
        ('PLATFORM_ADMIN', 'SECURITY.ROLE_ASSIGN'),
        ('PLATFORM_ADMIN', 'IDENTITY.READ'),
        ('PLATFORM_ADMIN', 'IDENTITY.WRITE'),
        ('PLATFORM_ADMIN', 'GEOGRAPHY.READ'),
        ('PLATFORM_ADMIN', 'GEOGRAPHY.WRITE'),
        ('PLATFORM_ADMIN', 'AIRLINE.READ'),
        ('PLATFORM_ADMIN', 'AIRLINE.WRITE'),
        ('PLATFORM_ADMIN', 'AIRPORT.READ'),
        ('PLATFORM_ADMIN', 'AIRPORT.WRITE'),
        ('PLATFORM_ADMIN', 'AIRCRAFT.READ'),
        ('PLATFORM_ADMIN', 'AIRCRAFT.WRITE'),
        ('PLATFORM_ADMIN', 'FLIGHT_OPS.READ'),
        ('PLATFORM_ADMIN', 'FLIGHT_OPS.WRITE'),
        ('PLATFORM_ADMIN', 'SALES.READ'),
        ('PLATFORM_ADMIN', 'SALES.WRITE'),
        ('PLATFORM_ADMIN', 'BOARDING.READ'),
        ('PLATFORM_ADMIN', 'BOARDING.WRITE'),
        ('PLATFORM_ADMIN', 'PAYMENT.READ'),
        ('PLATFORM_ADMIN', 'PAYMENT.WRITE'),
        ('PLATFORM_ADMIN', 'BILLING.READ'),
        ('PLATFORM_ADMIN', 'BILLING.WRITE'),
        ('PLATFORM_ADMIN', 'LOYALTY.READ'),
        ('PLATFORM_ADMIN', 'LOYALTY.WRITE'),
        ('PLATFORM_ADMIN', 'AUDIT.READ'),
        ('PLATFORM_ADMIN', 'AUDIT.WRITE'),
        ('PLATFORM_ADMIN', 'SYSTEM.CONFIGURE'),
        ('SECURITY_ADMIN', 'SECURITY.USERS_MANAGE'),
        ('SECURITY_ADMIN', 'SECURITY.ROLES_MANAGE'),
        ('SECURITY_ADMIN', 'SECURITY.PERMISSIONS_MANAGE'),
        ('SECURITY_ADMIN', 'SECURITY.ROLE_ASSIGN'),
        ('SECURITY_ADMIN', 'IDENTITY.READ'),
        ('SECURITY_ADMIN', 'AUDIT.READ'),
        ('OPERATIONS_AGENT', 'GEOGRAPHY.READ'),
        ('OPERATIONS_AGENT', 'AIRLINE.READ'),
        ('OPERATIONS_AGENT', 'AIRPORT.READ'),
        ('OPERATIONS_AGENT', 'AIRPORT.WRITE'),
        ('OPERATIONS_AGENT', 'AIRCRAFT.READ'),
        ('OPERATIONS_AGENT', 'AIRCRAFT.WRITE'),
        ('OPERATIONS_AGENT', 'FLIGHT_OPS.READ'),
        ('OPERATIONS_AGENT', 'FLIGHT_OPS.WRITE'),
        ('OPERATIONS_AGENT', 'BOARDING.READ'),
        ('OPERATIONS_AGENT', 'BOARDING.WRITE'),
        ('SALES_AGENT', 'SALES.READ'),
        ('SALES_AGENT', 'SALES.WRITE'),
        ('SALES_AGENT', 'BOARDING.READ'),
        ('SALES_AGENT', 'IDENTITY.READ'),
        ('SALES_AGENT', 'LOYALTY.READ'),
        ('FINANCE_ANALYST', 'PAYMENT.READ'),
        ('FINANCE_ANALYST', 'PAYMENT.WRITE'),
        ('FINANCE_ANALYST', 'BILLING.READ'),
        ('FINANCE_ANALYST', 'BILLING.WRITE'),
        ('FINANCE_ANALYST', 'SALES.READ'),
        ('LOYALTY_AGENT', 'LOYALTY.READ'),
        ('LOYALTY_AGENT', 'LOYALTY.WRITE'),
        ('LOYALTY_AGENT', 'IDENTITY.READ'),
        ('LOYALTY_AGENT', 'SALES.READ'),
        ('AUDITOR_READONLY', 'IDENTITY.READ'),
        ('AUDITOR_READONLY', 'GEOGRAPHY.READ'),
        ('AUDITOR_READONLY', 'AIRLINE.READ'),
        ('AUDITOR_READONLY', 'AIRPORT.READ'),
        ('AUDITOR_READONLY', 'AIRCRAFT.READ'),
        ('AUDITOR_READONLY', 'FLIGHT_OPS.READ'),
        ('AUDITOR_READONLY', 'SALES.READ'),
        ('AUDITOR_READONLY', 'BOARDING.READ'),
        ('AUDITOR_READONLY', 'PAYMENT.READ'),
        ('AUDITOR_READONLY', 'BILLING.READ'),
        ('AUDITOR_READONLY', 'LOYALTY.READ'),
        ('AUDITOR_READONLY', 'AUDIT.READ'),
        ('SUPPORT_AGENT', 'IDENTITY.READ'),
        ('SUPPORT_AGENT', 'IDENTITY.WRITE'),
        ('SUPPORT_AGENT', 'SALES.READ'),
        ('SUPPORT_AGENT', 'BOARDING.READ'),
        ('SUPPORT_AGENT', 'LOYALTY.READ')
)
INSERT INTO role_permission (security_role_id, security_permission_id)
SELECT sr.security_role_id, sp.security_permission_id
FROM role_perm rp
JOIN security_role sr
    ON sr.role_code = rp.role_code
JOIN security_permission sp
    ON sp.permission_code = rp.permission_code
ON CONFLICT (security_role_id, security_permission_id) DO NOTHING;
